[project]
name = "timeseries-transformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "neuralforecast>=3.1.4",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
]
